import os
import glob
import shlex
import subprocess
import tempfile
import psutil

from config import resolve_path, SETTINGS

PLAYBACK_VIDEO_DIR = resolve_path(SETTINGS["PLAYBACK_VIDEO_DIR"])
PLAYBACK_VIDEO_PATTERN = SETTINGS["PLAYBACK_VIDEO_PATTERN"]
PLAYBACK_PLAYER_PATH = resolve_path(SETTINGS["PLAYBACK_PLAYER_PATH"])
PLAYBACK_PLAYER_ARGS = SETTINGS["PLAYBACK_PLAYER_ARGS"]
PLAYBACK_PROCESS_NAME = SETTINGS["PLAYBACK_PROCESS_NAME"]
PLAYBACK_TIMEOUT_SECONDS = SETTINGS["PLAYBACK_TIMEOUT_SECONDS"]